"""Part 1 generation: seed -> plan -> critique.

Each API call runs in a FRESH context. The plan call sees only the seed text.
The critique call sees only the seed text and the plan. Neither sees our
bucket labels, our discriminators, or any other seed. This is the whole point:
a plan generated by a model that has already been told where the flaw is is
not a sample of what Claude produces cold, and measuring it tells us nothing.

Usage:
    python scripts/generate.py                        # all seeds, claude-opus-5
    python scripts/generate.py --model claude-haiku-4-5
    python scripts/generate.py --seeds S5 S10
"""

from __future__ import annotations

import argparse
import json
import pathlib
from concurrent.futures import ThreadPoolExecutor

import anthropic

ROOT = pathlib.Path(__file__).resolve().parent.parent
SEEDS_PATH = ROOT / "seeds.json"

PLAN_SYSTEM = """You are helping an investment researcher turn a half-formed research \
idea into an executable research plan.

Produce a plan the researcher could hand to an analyst and have them start Monday \
morning. Cover the hypothesis, the data required, the methodology, how the result \
will be validated, and the pitfalls you would watch for.

Write in plain prose. Be concrete about the choices you are making — specific \
datasets, specific estimators, specific thresholds — rather than gesturing at \
categories of choice."""

CRITIQUE_SYSTEM = """You are a senior portfolio manager running desk review on a \
research plan drafted by an analyst.

Your job is to find what is wrong with it — the things that would cause this work \
to produce a confident answer that does not survive contact with reality. Be \
specific about the failure: name the step, say what breaks, and say what it would \
take to fix or kill it.

If the underlying idea is not worth a full research project, say so and say what \
the cheaper version is. If the plan is sound, say that plainly rather than \
manufacturing objections."""


def build_client() -> anthropic.Anthropic:
    # Resolves ANTHROPIC_API_KEY, ANTHROPIC_AUTH_TOKEN, or an `ant auth login` profile.
    return anthropic.Anthropic()


def call(client: anthropic.Anthropic, model: str, system: str, prompt: str) -> str:
    # Stream: max_tokens is high enough that a non-streaming call risks an HTTP timeout.
    with client.messages.stream(
        model=model,
        max_tokens=32000,
        system=system,
        messages=[{"role": "user", "content": prompt}],
    ) as stream:
        message = stream.get_final_message()

    if message.stop_reason == "refusal":
        raise RuntimeError(f"refused: {message.stop_details}")

    return "\n".join(b.text for b in message.content if b.type == "text").strip()


def run_seed(client: anthropic.Anthropic, model: str, seed: dict, outdir: pathlib.Path) -> None:
    sid = seed["id"]

    plan = call(
        client,
        model,
        PLAN_SYSTEM,
        f"Here is the research idea:\n\n{seed['text']}\n\nWrite the research plan.",
    )
    (outdir / "plans" / f"{sid}.md").write_text(
        f"# {sid} — plan ({model})\n\n> {seed['text']}\n\n---\n\n{plan}\n"
    )

    critique = call(
        client,
        model,
        CRITIQUE_SYSTEM,
        f"The original research idea:\n\n{seed['text']}\n\n"
        f"The analyst's plan:\n\n{plan}\n\nReview it.",
    )
    (outdir / "critiques" / f"{sid}.md").write_text(
        f"# {sid} — critique ({model})\n\n> {seed['text']}\n\n---\n\n{critique}\n"
    )

    print(f"  {sid}: plan {len(plan):>6,} chars | critique {len(critique):>6,} chars")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="claude-opus-5")
    ap.add_argument("--seeds", nargs="*", help="seed ids; default all")
    ap.add_argument("--workers", type=int, default=4)
    args = ap.parse_args()

    seeds = json.loads(SEEDS_PATH.read_text())["seeds"]
    if args.seeds:
        wanted = set(args.seeds)
        seeds = [s for s in seeds if s["id"] in wanted]

    outdir = ROOT / "part1"
    (outdir / "plans").mkdir(parents=True, exist_ok=True)
    (outdir / "critiques").mkdir(parents=True, exist_ok=True)

    client = build_client()
    print(f"generating {len(seeds)} seeds on {args.model} -> {outdir.relative_to(ROOT)}/")

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        list(pool.map(lambda s: run_seed(client, args.model, s, outdir), seeds))

    print("done — now run: python scripts/collect.py")


if __name__ == "__main__":
    main()
