"""Render the Part 1 deliverable table from the merged raw.json.

Produces part1/findings-table.md — the assignment's
`# | seed | plan | critique | your_verdict` table, with your_verdict blank for
the human to fill in.

Usage:  python scripts/render_part1.py
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent


def squash(text: str, limit: int) -> str:
    """First substantive prose of a document, flattened into one table cell."""
    body: list[str] = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith(("#", ">", "-", "*", "|", "---", "=")):
            continue
        if re.fullmatch(r"\*\*.*\*\*", line):  # bold section label alone on a line
            continue
        body.append(line)
        if sum(len(b) for b in body) > limit:
            break
    out = re.sub(r"[*`_]", "", " ".join(body)).replace("|", "\\|")
    return (out[:limit].rsplit(" ", 1)[0] + " …") if len(out) > limit else out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--excerpt", type=int, default=300)
    args = ap.parse_args()

    seeds = {s["id"]: s for s in json.loads((ROOT / "seeds.json").read_text())["seeds"]}
    rows_in = json.loads((ROOT / "part1" / "raw.json").read_text())
    scores = {
        json.loads(p.read_text())["id"]: json.loads(p.read_text())
        for p in (ROOT / "part1" / "scores").glob("*.json")
    }

    rows = []
    for n, r in enumerate(rows_in, start=1):
        sid = r["id"]
        seed = seeds[sid]
        verdict = scores.get(sid, {}).get("verdict_line", "")
        rows.append(
            "| {n} | **{sid}** · {style} · {bucket}<br>{text} "
            "| {plan}<br><sub>[full](plans/{sid}.md)</sub> "
            "| {crit}<br><sub>[full](critiques/{sid}.md)</sub> "
            "|  |<!-- suggested: {v} -->".format(
                n=n,
                sid=sid,
                style=seed["style"],
                bucket=seed["bucket"],
                text=squash(seed["text"], 170),
                plan=squash(r["plan"], args.excerpt),
                crit=squash(r["critique"], args.excerpt),
                v=verdict.replace("|", "/"),
            )
        )

    doc = (
        "# Part 1 — seed / plan / critique / verdict\n\n"
        "Plans and critiques were generated by models that never saw the known flaw, the "
        "bucket label, or any sibling seed — see `PROVENANCE.md`. `your_verdict` is "
        "deliberately empty: it is the human column, and the assignment scores Claude "
        "against *your* instinct, not mine. An HTML comment on each row carries the "
        "independent scorer's one-line read as a starting point.\n\n"
        "Scorecard with recall / precision / right-sizing: `scorecard.md`.\n\n"
        "| # | seed | plan (Claude) | critique (Claude) | your_verdict |\n"
        "|---|---|---|---|---|\n" + "\n".join(rows) + "\n"
    )
    out = ROOT / "part1" / "findings-table.md"
    out.write_text(doc)
    print(f"wrote {out.relative_to(ROOT)} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
